/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as SettingsExecutionRouteImport } from './routes/settings.execution'
import { Route as SettingsNotifyRouteImport } from './routes/settings.notify'
import { Route as SettingsParamsRouteImport } from './routes/settings.params'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ApiInspectShotIdRouteImport } from './routes/api/inspect-shot.$id'
import { Route as ApiPublicAgentAiConfigRouteImport } from './routes/api/public/agent/ai-config'
import { Route as ApiPublicAgentBrowsersRouteImport } from './routes/api/public/agent/browsers'
import { Route as ApiPublicAgentCasesRouteImport } from './routes/api/public/agent/cases'
import { Route as ApiPublicAgentInspectRouteImport } from './routes/api/public/agent/inspect'
import { Route as ApiPublicAgentJobsRouteImport } from './routes/api/public/agent/jobs'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicAgentReleaseRouteImport } from './routes/api/public/agent/release'
import { Route as ApiPublicAgentResolveRouteImport } from './routes/api/public/agent/resolve'
import { Route as ApiPublicAgentRunReportRouteImport } from './routes/api/public/agent/run-report'
import { Route as ApiPublicAgentUpgradeRouteImport } from './routes/api/public/agent/upgrade'
import { Route as ApiPublicAgentUpgradeReportRouteImport } from './routes/api/public/agent/upgrade-report'
import { Route as ApiPublicAgentVersionRouteImport } from './routes/api/public/agent/version'
import { Route as ApiPublicBrowserMirrorSplatRouteImport } from './routes/api/public/browser-mirror.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExecutionRoute = SettingsExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotifyRoute = SettingsNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsParamsRoute = SettingsParamsRouteImport.update({
  id: '/params',
  path: '/params',
  getParentRoute: () => SettingsRoute,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInspectShotIdRoute = ApiInspectShotIdRouteImport.update({
  id: '/api/inspect-shot/$id',
  path: '/api/inspect-shot/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAiConfigRoute = ApiPublicAgentAiConfigRouteImport.update({
  id: '/api/public/agent/ai-config',
  path: '/api/public/agent/ai-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentBrowsersRoute = ApiPublicAgentBrowsersRouteImport.update({
  id: '/api/public/agent/browsers',
  path: '/api/public/agent/browsers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCasesRoute = ApiPublicAgentCasesRouteImport.update({
  id: '/api/public/agent/cases',
  path: '/api/public/agent/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentInspectRoute = ApiPublicAgentInspectRouteImport.update({
  id: '/api/public/agent/inspect',
  path: '/api/public/agent/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentJobsRoute = ApiPublicAgentJobsRouteImport.update({
  id: '/api/public/agent/jobs',
  path: '/api/public/agent/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentReleaseRoute = ApiPublicAgentReleaseRouteImport.update({
  id: '/api/public/agent/release',
  path: '/api/public/agent/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentResolveRoute = ApiPublicAgentResolveRouteImport.update({
  id: '/api/public/agent/resolve',
  path: '/api/public/agent/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRunReportRoute = ApiPublicAgentRunReportRouteImport.update({
  id: '/api/public/agent/run-report',
  path: '/api/public/agent/run-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUpgradeRoute = ApiPublicAgentUpgradeRouteImport.update({
  id: '/api/public/agent/upgrade',
  path: '/api/public/agent/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUpgradeReportRoute =
  ApiPublicAgentUpgradeReportRouteImport.update({
    id: '/api/public/agent/upgrade-report',
    path: '/api/public/agent/upgrade-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentVersionRoute = ApiPublicAgentVersionRouteImport.update({
  id: '/api/public/agent/version',
  path: '/api/public/agent/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrowserMirrorSplatRoute =
  ApiPublicBrowserMirrorSplatRouteImport.update({
    id: '/api/public/browser-mirror/$',
    path: '/api/public/browser-mirror/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/agents': typeof AgentsRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/download': typeof DownloadRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/execution': typeof SettingsExecutionRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/settings/params': typeof SettingsParamsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/cases/': typeof CasesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/inspect-shot/$id': typeof ApiInspectShotIdRoute
  '/api/public/agent/ai-config': typeof ApiPublicAgentAiConfigRoute
  '/api/public/agent/browsers': typeof ApiPublicAgentBrowsersRoute
  '/api/public/agent/cases': typeof ApiPublicAgentCasesRoute
  '/api/public/agent/inspect': typeof ApiPublicAgentInspectRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/release': typeof ApiPublicAgentReleaseRoute
  '/api/public/agent/resolve': typeof ApiPublicAgentResolveRoute
  '/api/public/agent/run-report': typeof ApiPublicAgentRunReportRoute
  '/api/public/agent/upgrade': typeof ApiPublicAgentUpgradeRoute
  '/api/public/agent/upgrade-report': typeof ApiPublicAgentUpgradeReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
  '/api/public/browser-mirror/$': typeof ApiPublicBrowserMirrorSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/agents': typeof AgentsRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/download': typeof DownloadRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/execution': typeof SettingsExecutionRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/settings/params': typeof SettingsParamsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/cases': typeof CasesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/inspect-shot/$id': typeof ApiInspectShotIdRoute
  '/api/public/agent/ai-config': typeof ApiPublicAgentAiConfigRoute
  '/api/public/agent/browsers': typeof ApiPublicAgentBrowsersRoute
  '/api/public/agent/cases': typeof ApiPublicAgentCasesRoute
  '/api/public/agent/inspect': typeof ApiPublicAgentInspectRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/release': typeof ApiPublicAgentReleaseRoute
  '/api/public/agent/resolve': typeof ApiPublicAgentResolveRoute
  '/api/public/agent/run-report': typeof ApiPublicAgentRunReportRoute
  '/api/public/agent/upgrade': typeof ApiPublicAgentUpgradeRoute
  '/api/public/agent/upgrade-report': typeof ApiPublicAgentUpgradeReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
  '/api/public/browser-mirror/$': typeof ApiPublicBrowserMirrorSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/agents': typeof AgentsRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/download': typeof DownloadRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/execution': typeof SettingsExecutionRoute
  '/settings/notify': typeof SettingsNotifyRoute
  '/settings/params': typeof SettingsParamsRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/cases/': typeof CasesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/inspect-shot/$id': typeof ApiInspectShotIdRoute
  '/api/public/agent/ai-config': typeof ApiPublicAgentAiConfigRoute
  '/api/public/agent/browsers': typeof ApiPublicAgentBrowsersRoute
  '/api/public/agent/cases': typeof ApiPublicAgentCasesRoute
  '/api/public/agent/inspect': typeof ApiPublicAgentInspectRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/release': typeof ApiPublicAgentReleaseRoute
  '/api/public/agent/resolve': typeof ApiPublicAgentResolveRoute
  '/api/public/agent/run-report': typeof ApiPublicAgentRunReportRoute
  '/api/public/agent/upgrade': typeof ApiPublicAgentUpgradeRoute
  '/api/public/agent/upgrade-report': typeof ApiPublicAgentUpgradeReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
  '/api/public/browser-mirror/$': typeof ApiPublicBrowserMirrorSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-dashboard'
    | '/agents'
    | '/ai'
    | '/auth'
    | '/board'
    | '/download'
    | '/live'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/cases/$caseId'
    | '/settings/agents'
    | '/settings/ai'
    | '/settings/execution'
    | '/settings/notify'
    | '/settings/params'
    | '/tasks/$taskId'
    | '/cases/'
    | '/settings/'
    | '/tasks/'
    | '/api/inspect-shot/$id'
    | '/api/public/agent/ai-config'
    | '/api/public/agent/browsers'
    | '/api/public/agent/cases'
    | '/api/public/agent/inspect'
    | '/api/public/agent/jobs'
    | '/api/public/agent/register'
    | '/api/public/agent/release'
    | '/api/public/agent/resolve'
    | '/api/public/agent/run-report'
    | '/api/public/agent/upgrade'
    | '/api/public/agent/upgrade-report'
    | '/api/public/agent/version'
    | '/api/public/browser-mirror/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-dashboard'
    | '/agents'
    | '/ai'
    | '/auth'
    | '/board'
    | '/download'
    | '/live'
    | '/reports'
    | '/api/chat'
    | '/cases/$caseId'
    | '/settings/agents'
    | '/settings/ai'
    | '/settings/execution'
    | '/settings/notify'
    | '/settings/params'
    | '/tasks/$taskId'
    | '/cases'
    | '/settings'
    | '/tasks'
    | '/api/inspect-shot/$id'
    | '/api/public/agent/ai-config'
    | '/api/public/agent/browsers'
    | '/api/public/agent/cases'
    | '/api/public/agent/inspect'
    | '/api/public/agent/jobs'
    | '/api/public/agent/register'
    | '/api/public/agent/release'
    | '/api/public/agent/resolve'
    | '/api/public/agent/run-report'
    | '/api/public/agent/upgrade'
    | '/api/public/agent/upgrade-report'
    | '/api/public/agent/version'
    | '/api/public/browser-mirror/$'
  id:
    | '__root__'
    | '/'
    | '/agent-dashboard'
    | '/agents'
    | '/ai'
    | '/auth'
    | '/board'
    | '/download'
    | '/live'
    | '/reports'
    | '/settings'
    | '/api/chat'
    | '/cases/$caseId'
    | '/settings/agents'
    | '/settings/ai'
    | '/settings/execution'
    | '/settings/notify'
    | '/settings/params'
    | '/tasks/$taskId'
    | '/cases/'
    | '/settings/'
    | '/tasks/'
    | '/api/inspect-shot/$id'
    | '/api/public/agent/ai-config'
    | '/api/public/agent/browsers'
    | '/api/public/agent/cases'
    | '/api/public/agent/inspect'
    | '/api/public/agent/jobs'
    | '/api/public/agent/register'
    | '/api/public/agent/release'
    | '/api/public/agent/resolve'
    | '/api/public/agent/run-report'
    | '/api/public/agent/upgrade'
    | '/api/public/agent/upgrade-report'
    | '/api/public/agent/version'
    | '/api/public/browser-mirror/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentsRoute: typeof AgentsRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  BoardRoute: typeof BoardRoute
  DownloadRoute: typeof DownloadRoute
  LiveRoute: typeof LiveRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiInspectShotIdRoute: typeof ApiInspectShotIdRoute
  ApiPublicAgentAiConfigRoute: typeof ApiPublicAgentAiConfigRoute
  ApiPublicAgentBrowsersRoute: typeof ApiPublicAgentBrowsersRoute
  ApiPublicAgentCasesRoute: typeof ApiPublicAgentCasesRoute
  ApiPublicAgentInspectRoute: typeof ApiPublicAgentInspectRoute
  ApiPublicAgentJobsRoute: typeof ApiPublicAgentJobsRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentReleaseRoute: typeof ApiPublicAgentReleaseRoute
  ApiPublicAgentResolveRoute: typeof ApiPublicAgentResolveRoute
  ApiPublicAgentRunReportRoute: typeof ApiPublicAgentRunReportRoute
  ApiPublicAgentUpgradeRoute: typeof ApiPublicAgentUpgradeRoute
  ApiPublicAgentUpgradeReportRoute: typeof ApiPublicAgentUpgradeReportRoute
  ApiPublicAgentVersionRoute: typeof ApiPublicAgentVersionRoute
  ApiPublicBrowserMirrorSplatRoute: typeof ApiPublicBrowserMirrorSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/execution': {
      id: '/settings/execution'
      path: '/execution'
      fullPath: '/settings/execution'
      preLoaderRoute: typeof SettingsExecutionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notify': {
      id: '/settings/notify'
      path: '/notify'
      fullPath: '/settings/notify'
      preLoaderRoute: typeof SettingsNotifyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/params': {
      id: '/settings/params'
      path: '/params'
      fullPath: '/settings/params'
      preLoaderRoute: typeof SettingsParamsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inspect-shot/$id': {
      id: '/api/inspect-shot/$id'
      path: '/api/inspect-shot/$id'
      fullPath: '/api/inspect-shot/$id'
      preLoaderRoute: typeof ApiInspectShotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/ai-config': {
      id: '/api/public/agent/ai-config'
      path: '/api/public/agent/ai-config'
      fullPath: '/api/public/agent/ai-config'
      preLoaderRoute: typeof ApiPublicAgentAiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/browsers': {
      id: '/api/public/agent/browsers'
      path: '/api/public/agent/browsers'
      fullPath: '/api/public/agent/browsers'
      preLoaderRoute: typeof ApiPublicAgentBrowsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/cases': {
      id: '/api/public/agent/cases'
      path: '/api/public/agent/cases'
      fullPath: '/api/public/agent/cases'
      preLoaderRoute: typeof ApiPublicAgentCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/inspect': {
      id: '/api/public/agent/inspect'
      path: '/api/public/agent/inspect'
      fullPath: '/api/public/agent/inspect'
      preLoaderRoute: typeof ApiPublicAgentInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/jobs': {
      id: '/api/public/agent/jobs'
      path: '/api/public/agent/jobs'
      fullPath: '/api/public/agent/jobs'
      preLoaderRoute: typeof ApiPublicAgentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/release': {
      id: '/api/public/agent/release'
      path: '/api/public/agent/release'
      fullPath: '/api/public/agent/release'
      preLoaderRoute: typeof ApiPublicAgentReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/resolve': {
      id: '/api/public/agent/resolve'
      path: '/api/public/agent/resolve'
      fullPath: '/api/public/agent/resolve'
      preLoaderRoute: typeof ApiPublicAgentResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/run-report': {
      id: '/api/public/agent/run-report'
      path: '/api/public/agent/run-report'
      fullPath: '/api/public/agent/run-report'
      preLoaderRoute: typeof ApiPublicAgentRunReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/upgrade': {
      id: '/api/public/agent/upgrade'
      path: '/api/public/agent/upgrade'
      fullPath: '/api/public/agent/upgrade'
      preLoaderRoute: typeof ApiPublicAgentUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/upgrade-report': {
      id: '/api/public/agent/upgrade-report'
      path: '/api/public/agent/upgrade-report'
      fullPath: '/api/public/agent/upgrade-report'
      preLoaderRoute: typeof ApiPublicAgentUpgradeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/version': {
      id: '/api/public/agent/version'
      path: '/api/public/agent/version'
      fullPath: '/api/public/agent/version'
      preLoaderRoute: typeof ApiPublicAgentVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/browser-mirror/$': {
      id: '/api/public/browser-mirror/$'
      path: '/api/public/browser-mirror/$'
      fullPath: '/api/public/browser-mirror/$'
      preLoaderRoute: typeof ApiPublicBrowserMirrorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsExecutionRoute: typeof SettingsExecutionRoute
  SettingsNotifyRoute: typeof SettingsNotifyRoute
  SettingsParamsRoute: typeof SettingsParamsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsExecutionRoute: SettingsExecutionRoute,
  SettingsNotifyRoute: SettingsNotifyRoute,
  SettingsParamsRoute: SettingsParamsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentsRoute: AgentsRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  BoardRoute: BoardRoute,
  DownloadRoute: DownloadRoute,
  LiveRoute: LiveRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiInspectShotIdRoute: ApiInspectShotIdRoute,
  ApiPublicAgentAiConfigRoute: ApiPublicAgentAiConfigRoute,
  ApiPublicAgentBrowsersRoute: ApiPublicAgentBrowsersRoute,
  ApiPublicAgentCasesRoute: ApiPublicAgentCasesRoute,
  ApiPublicAgentInspectRoute: ApiPublicAgentInspectRoute,
  ApiPublicAgentJobsRoute: ApiPublicAgentJobsRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentReleaseRoute: ApiPublicAgentReleaseRoute,
  ApiPublicAgentResolveRoute: ApiPublicAgentResolveRoute,
  ApiPublicAgentRunReportRoute: ApiPublicAgentRunReportRoute,
  ApiPublicAgentUpgradeRoute: ApiPublicAgentUpgradeRoute,
  ApiPublicAgentUpgradeReportRoute: ApiPublicAgentUpgradeReportRoute,
  ApiPublicAgentVersionRoute: ApiPublicAgentVersionRoute,
  ApiPublicBrowserMirrorSplatRoute: ApiPublicBrowserMirrorSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
