/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DesktopRouteImport } from './routes/desktop'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ApiPublicAgentCasesRouteImport } from './routes/api/public/agent/cases'
import { Route as ApiPublicAgentJobsRouteImport } from './routes/api/public/agent/jobs'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicAgentRunReportRouteImport } from './routes/api/public/agent/run-report'
import { Route as ApiPublicAgentUpgradeRouteImport } from './routes/api/public/agent/upgrade'
import { Route as ApiPublicAgentUpgradeReportRouteImport } from './routes/api/public/agent/upgrade-report'
import { Route as ApiPublicAgentVersionRouteImport } from './routes/api/public/agent/version'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCasesRoute = ApiPublicAgentCasesRouteImport.update({
  id: '/api/public/agent/cases',
  path: '/api/public/agent/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentJobsRoute = ApiPublicAgentJobsRouteImport.update({
  id: '/api/public/agent/jobs',
  path: '/api/public/agent/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRunReportRoute = ApiPublicAgentRunReportRouteImport.update({
  id: '/api/public/agent/run-report',
  path: '/api/public/agent/run-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUpgradeRoute = ApiPublicAgentUpgradeRouteImport.update({
  id: '/api/public/agent/upgrade',
  path: '/api/public/agent/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentUpgradeReportRoute =
  ApiPublicAgentUpgradeReportRouteImport.update({
    id: '/api/public/agent/upgrade-report',
    path: '/api/public/agent/upgrade-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentVersionRoute = ApiPublicAgentVersionRouteImport.update({
  id: '/api/public/agent/version',
  path: '/api/public/agent/version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRoute
  '/desktop': typeof DesktopRoute
  '/download': typeof DownloadRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/cases/': typeof CasesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/agent/cases': typeof ApiPublicAgentCasesRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/run-report': typeof ApiPublicAgentRunReportRoute
  '/api/public/agent/upgrade': typeof ApiPublicAgentUpgradeRoute
  '/api/public/agent/upgrade-report': typeof ApiPublicAgentUpgradeReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRoute
  '/desktop': typeof DesktopRoute
  '/download': typeof DownloadRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/cases': typeof CasesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/api/public/agent/cases': typeof ApiPublicAgentCasesRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/run-report': typeof ApiPublicAgentRunReportRoute
  '/api/public/agent/upgrade': typeof ApiPublicAgentUpgradeRoute
  '/api/public/agent/upgrade-report': typeof ApiPublicAgentUpgradeReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/board': typeof BoardRoute
  '/desktop': typeof DesktopRoute
  '/download': typeof DownloadRoute
  '/live': typeof LiveRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/cases/': typeof CasesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/api/public/agent/cases': typeof ApiPublicAgentCasesRoute
  '/api/public/agent/jobs': typeof ApiPublicAgentJobsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/run-report': typeof ApiPublicAgentRunReportRoute
  '/api/public/agent/upgrade': typeof ApiPublicAgentUpgradeRoute
  '/api/public/agent/upgrade-report': typeof ApiPublicAgentUpgradeReportRoute
  '/api/public/agent/version': typeof ApiPublicAgentVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/board'
    | '/desktop'
    | '/download'
    | '/live'
    | '/reports'
    | '/settings'
    | '/cases/$caseId'
    | '/tasks/$taskId'
    | '/cases/'
    | '/tasks/'
    | '/api/public/agent/cases'
    | '/api/public/agent/jobs'
    | '/api/public/agent/register'
    | '/api/public/agent/run-report'
    | '/api/public/agent/upgrade'
    | '/api/public/agent/upgrade-report'
    | '/api/public/agent/version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/board'
    | '/desktop'
    | '/download'
    | '/live'
    | '/reports'
    | '/settings'
    | '/cases/$caseId'
    | '/tasks/$taskId'
    | '/cases'
    | '/tasks'
    | '/api/public/agent/cases'
    | '/api/public/agent/jobs'
    | '/api/public/agent/register'
    | '/api/public/agent/run-report'
    | '/api/public/agent/upgrade'
    | '/api/public/agent/upgrade-report'
    | '/api/public/agent/version'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/board'
    | '/desktop'
    | '/download'
    | '/live'
    | '/reports'
    | '/settings'
    | '/cases/$caseId'
    | '/tasks/$taskId'
    | '/cases/'
    | '/tasks/'
    | '/api/public/agent/cases'
    | '/api/public/agent/jobs'
    | '/api/public/agent/register'
    | '/api/public/agent/run-report'
    | '/api/public/agent/upgrade'
    | '/api/public/agent/upgrade-report'
    | '/api/public/agent/version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  BoardRoute: typeof BoardRoute
  DesktopRoute: typeof DesktopRoute
  DownloadRoute: typeof DownloadRoute
  LiveRoute: typeof LiveRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ApiPublicAgentCasesRoute: typeof ApiPublicAgentCasesRoute
  ApiPublicAgentJobsRoute: typeof ApiPublicAgentJobsRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentRunReportRoute: typeof ApiPublicAgentRunReportRoute
  ApiPublicAgentUpgradeRoute: typeof ApiPublicAgentUpgradeRoute
  ApiPublicAgentUpgradeReportRoute: typeof ApiPublicAgentUpgradeReportRoute
  ApiPublicAgentVersionRoute: typeof ApiPublicAgentVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop': {
      id: '/desktop'
      path: '/desktop'
      fullPath: '/desktop'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/cases': {
      id: '/api/public/agent/cases'
      path: '/api/public/agent/cases'
      fullPath: '/api/public/agent/cases'
      preLoaderRoute: typeof ApiPublicAgentCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/jobs': {
      id: '/api/public/agent/jobs'
      path: '/api/public/agent/jobs'
      fullPath: '/api/public/agent/jobs'
      preLoaderRoute: typeof ApiPublicAgentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/run-report': {
      id: '/api/public/agent/run-report'
      path: '/api/public/agent/run-report'
      fullPath: '/api/public/agent/run-report'
      preLoaderRoute: typeof ApiPublicAgentRunReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/upgrade': {
      id: '/api/public/agent/upgrade'
      path: '/api/public/agent/upgrade'
      fullPath: '/api/public/agent/upgrade'
      preLoaderRoute: typeof ApiPublicAgentUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/upgrade-report': {
      id: '/api/public/agent/upgrade-report'
      path: '/api/public/agent/upgrade-report'
      fullPath: '/api/public/agent/upgrade-report'
      preLoaderRoute: typeof ApiPublicAgentUpgradeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/version': {
      id: '/api/public/agent/version'
      path: '/api/public/agent/version'
      fullPath: '/api/public/agent/version'
      preLoaderRoute: typeof ApiPublicAgentVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  BoardRoute: BoardRoute,
  DesktopRoute: DesktopRoute,
  DownloadRoute: DownloadRoute,
  LiveRoute: LiveRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ApiPublicAgentCasesRoute: ApiPublicAgentCasesRoute,
  ApiPublicAgentJobsRoute: ApiPublicAgentJobsRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentRunReportRoute: ApiPublicAgentRunReportRoute,
  ApiPublicAgentUpgradeRoute: ApiPublicAgentUpgradeRoute,
  ApiPublicAgentUpgradeReportRoute: ApiPublicAgentUpgradeReportRoute,
  ApiPublicAgentVersionRoute: ApiPublicAgentVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
